### ISSUE TITLE
Meta tracker

### ISSUE THREAD

**Issue by zhaofengli** [blumonks/android_device_blu_p6601#6]
## Bare Essentials
- [x] Booting
- [x] RIL
- [x] Bluetooth
- [x] Wi-Fi
    - [x] Client
    - [x] Hotspot (#7)
- [x] GPS (#5)
- [ ] Camera (#1)
- [ ] Flashlight (#2)
- [x] Auto Rotate/Accelerometer (#8)

## Security
- [ ] SELinux enforcing (#4)
- [x] Security patches
    - Currently patched all the way up to May security bulletin. Should we create an issue every month, or make a single issue to track this?

## Misc
- [x] Recovery
    - [x] TWRP (https://github.com/blumonks/twrp_device_blu_p6601)
    - [x] CWM (verified by @jianC at jianC/android_p6601#1)
- [ ] VoLTE

**Comment by natekc** [comment]
I don't think we need to create an issue every month for security.  It's nice to have but is not essential.

**Comment by natekc** [comment]
Speaking of security, the kernel now includes fix for blueborne bluetooth vulnerability :)
